### ISSUE TITLE
App crashes before start

### ISSUE THREAD

**Issue by Rebolon** [iDoMeteor/MeteorPress#1]
When trying to install the app following the README.md it fails :

cd meteorpress && meteor 
nothing happen except if we add --verbose params.
Then we got : 

=> Errors prevented startup:

   While building the application:
   meteorpress\client\themes\boostrap-text-only-dark\vanilla.less:1:1:
   Less compiler error: '/packages/bootstrap-less/bootstrap.less' wasn't
   found

=> Your application has errors. Waiting for file change.

**Comment by iDoMeteor** [comment]
This version of MeteorPress is beta 3 in progress and is not in a functional state and is on pause for a few more weeks until I finish #OnePageWonder.  If you want to check out beta 2, which is still working pretty well using autoform in the admin area.  If you would like me to send you that version as a tarball, mention me @ Twitter or email me directly @ gmail.  I /just/ set it up on http://blog.idometeor.com yesterday.
